name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 2.0.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.emr.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/users/User1@org1.emr.com/msp/keystore/e3201399ccb3cbf21926558971fcfe50f0cfcda2e52e271cf364a22e6a1a32bb_sk
      clientSignedCert:
        path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/users/User1@org1.emr.com/msp/signcerts/cert.pem

  client0.org2.emr.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/users/User1@org2.emr.com/msp/keystore/60ff483b130698bb712675dfebac223f3d5f55fb6bd608b6e98dfd5baa33989e_sk
      clientSignedCert:
        path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/users/User1@org2.emr.com/msp/signcerts/cert.pem

channels:
  emr-channel:
    # configBinary: /home/linhpnguyen/LVCNTT/emr-hyperledger/emr-network/mychannel.tx
    created: true
    definition:
      capabilities: []
      consortium: "SampleConsortium"
      msps: ["Org1MSP", "Org2MSP"]
      version: 0
    orderers:
      - orderer.emr.com
    peers:
      peer0.org1.emr.com:
        eventSource: true
      peer0.org2.emr.com:
        eventSource: true

    chaincodes:
      - id: emr-chaincode
        version: "1"
        language: node
        path: /home/linhpnguyen/LVCNTT/emr-hyperledger/chaincode/admin/lib

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.emr.com
    certificateAuthorities:
      - ca.org1.emr.com
    adminPrivateKey:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/users/Admin@org1.emr.com/msp/keystore/c5c9ffbdd5742cf5ad98a6c6066db005a1a06316e622112f993324ab30c8fbf2_sk
    signedCert:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/users/Admin@org1.emr.com/msp/signcerts/cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.emr.com
    certificateAuthorities:
      - ca.org2.emr.com
    adminPrivateKey:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/users/Admin@org2.emr.com/msp/keystore/c5c9ffbdd5742cf5ad98a6c6066db005a1a06316e622112f993324ab30c8fbf2_sk
    signedCert:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/users/Admin@org2.emr.com/msp/signcerts/cert.pem

orderers:
  orderer.emr.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.emr.com
    tlsCACerts:
      path: /hyperledger/caliper/workspace/organizations/ordererOrganizations/emr.com/orderers/orderer.emr.com/msp/tlscacerts/tlsca.emr.com-cert.pem

peers:
  peer0.org1.emr.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.emr.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/peers/peer0.org1.emr.com/tls/tlscacerts/tls-localhost-7054-ca-org1.pem

  peer0.org2.emr.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.emr.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/peers/peer0.org2.emr.com/tls/tlscacerts/tls-localhost-8054-ca-org2.pem

certificateAuthorities:
  ca.org1.emr.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org1.emr.com/tlsca/tlsca.org1.emr.com-cert.pem
    # registrar:
    #   - enrollId: admin
    #     enrollSecret: adminpw

  ca.org2.emr.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /hyperledger/caliper/workspace/organizations/peerOrganizations/org2.emr.com/tlsca/tlsca.org2.emr.com-cert.pem
    # registrar:
    #   - enrollId: admin
    #     enrollSecret: adminpw
